version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "8432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shop_api
    volumes:
    - data01:/var/lib/postgresql/data
volumes:
  data01:
    driver: local
